export type Deal = {
  [key: string]: string | null | Array<any> | boolean;
  ID: string;
  TITLE: string;
  TYPE_ID: string;
  STAGE_ID: string;
  PROBABILITY: string | null;
  CURRENCY_ID: string;
  OPPORTUNITY: string;
  IS_MANUAL_OPPORTUNITY: 'Y' | 'N';
  TAX_VALUE: string;
  LEAD_ID: string | null;
  COMPANY_ID: string;
  CONTACT_ID: string | null;
  QUOTE_ID: string | null;
  BEGINDATE: string;
  CLOSEDATE: string;
  ASSIGNED_BY_ID: string;
  CREATED_BY_ID: string;
  MODIFY_BY_ID: string;
  DATE_CREATE: string;
  DATE_MODIFY: string;
  OPENED: 'Y' | 'N';
  CLOSED: 'Y' | 'N';
  COMMENTS: string;
  ADDITIONAL_INFO: string | null;
  LOCATION_ID: string | null;
  CATEGORY_ID: string;
  STAGE_SEMANTIC_ID: string;
  IS_NEW: 'Y' | 'N';
  IS_RECURRING: 'Y' | 'N';
  IS_RETURN_CUSTOMER: 'Y' | 'N';
  IS_REPEATED_APPROACH: 'Y' | 'N';
  SOURCE_ID: string;
  SOURCE_DESCRIPTION: string;
  ORIGINATOR_ID: string | null;
  ORIGIN_ID: string | null;
  MOVED_BY_ID: string;
  MOVED_TIME: string;
  LAST_ACTIVITY_TIME: string;
  UTM_SOURCE: string | null;
  UTM_MEDIUM: string | null;
  UTM_CAMPAIGN: string | null;
  UTM_CONTENT: string | null;
  UTM_TERM: string | null;
  LAST_ACTIVITY_BY: string;
};
