type TPhone = {
  ID: string;
  VALUE_TYPE: string;
  VALUR: string;
  TYPE_ID: 'PHONE';
};

type TEmail = {
  ID: string;
  VALUE_TYPE: string;
  VALUR: string;
  TYPE_ID: 'EMAIL';
};

export type Contact = {
  [key: string]: string | null | Array<any> | boolean;
  ID: string;
  POST: string | null;
  COMMENTS: string;
  HONORIFIC: string | null;
  NAME: string;
  SECOND_NAME: string | null;
  LAST_NAME: string;
  PHOTO: string | null;
  LEAD_ID: string | null;
  TYPE_ID: string;
  SOURCE_ID: string;
  SOURCE_DESCRIPTION: string;
  COMPANY_ID: string | null;
  BIRTHDATE: string;
  EXPORT: 'Y' | 'N';
  HAS_PHONE: 'Y' | 'N';
  HAS_EMAIL: 'Y' | 'N';
  HAS_IMOL: 'Y' | 'N';
  DATE_CREATE: string;
  DATE_MODIFY: string;
  ASSIGNED_BY_ID: string;
  CREATED_BY_ID: string;
  MODIFY_BY_ID: string;
  OPENED: 'Y' | 'N';
  ORIGINATOR_ID: string | null;
  ORIGIN_ID: string | null;
  ORIGIN_VERSION: string | null;
  FACE_ID: string | null;
  LAST_ACTIVITY_TIME: string;
  ADDRESS: string | null;
  ADDRESS_2: string | null;
  ADDRESS_CITY: string | null;
  ADDRESS_POSTAL_CODE: string | null;
  ADDRESS_REGION: string | null;
  ADDRESS_PROVINCE: string | null;
  ADDRESS_COUNTRY: string | null;
  ADDRESS_LOC_ADDR_ID: string | null;
  UTM_SOURCE: string | null;
  UTM_MEDIUM: string | null;
  UTM_CAMPAIGN: string | null;
  UTM_CONTENT: string | null;
  UTM_TERM: string | null;
  LAST_ACTIVITY_BY: string;
  EMAIL: TEmail[] | null;
  PHONE: TPhone[] | null;
};
